### ISSUE TITLE
El programa deja de funcionar

### ISSUE THREAD

**Issue by fer852** [HeberonYT/MultiMinecraft#1]
hola buen dia, El problema es que el programa de fucionar al darle a play,  en cualquer intancia lo probe en 2 pcs y hace lo mismo

**Comment by HeberonYT** [comment]
Gracias por el reporte.
Al iniciar una instancia se ejecuta el launcher de Minecraft? O nunca aparece?

**Comment by fer852** [comment]
Hola buen día, en ocasiones sólo se cierra pero no es muy frecuente

**Comment by HeberonYT** [comment]
Solucionado, esta corrección estará disponible en la siguiente actualización v2.6.5
