### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by santisgo** [HeberonYT/MultiMinecraft#10]
lo que paso cuando descargue multiminecraft 2 normal es que me aparecieron instancias con mods que nunca habia creado y no las puedo borrar me sale las instancias huellitas,lol,munecraft y otra sin nombre y yo nunca las cree espero que lo solucionen,saludos

**Comment by HeberonYT** [comment]
Hola, si quieres borrar esas instancias con fuerza bruta, sigue los pasos que están en la imagen.
Recuerda que no podrás recuperarlas si son eliminadas.
![screenshot_1](https://user-images.githubusercontent.com/13698597/35188393-2cd008c8-fdfa-11e7-840a-601f63dd7fa9.png)

**Comment by santisgo** [comment]
gracias :)

2018-01-20 18:54 GMT-03:00 HeberonYT <notifications@github.com>:
