### ISSUE TITLE
Nombre de instancias

### ISSUE THREAD

**Issue by jonathanfernandezfm** [HeberonYT/MultiMinecraft#11]
Que aparezca el nombre de la instancia en vez de el numero, ya que cuesta a veces identificarlas, y el nombre que se le da tiene 0 uso

**Comment by HeberonYT** [comment]
Hola!
El nombre aparece si tienes seleccionada la vista "Vertical", ademas de aparecer en un globo de texto cuando dejas el cursos sobre el icono de la instancia.
Pero entiendo lo que mencionas, así que he realizado algunos cambios, esta actualización será publicada pronto.
Gracias por el aporte!
![screenshot_2](https://user-images.githubusercontent.com/13698597/35188348-4e332820-fdf9-11e7-8c01-0d4fd5dcf73e.png)
