### ISSUE TITLE
Problema con journeymap , desde la ultima actualización

### ISSUE THREAD

**Issue by c4rli7rox** [HeberonYT/MultiMinecraft#12]
Estimado.

Primero que todo quiero agradecer tu esfuerzo y por tratar de dar siempre lo mejor en tus softwares , estoy muy contento con tus modpack , me han salvado la vida con mi hijo muchas veces. pero desde que se actualizo hay un problema con el mod journeymap, no deja teletrasportarse a los waypoints , incluso en modo creativo. tengo un vídeo pero no se como compartirlo. estaría muy agradecido si me leyeras y me ayudases a resolver este problema. de ante mano muchas gracias por tu valioso tiempo.

**Comment by HeberonYT** [comment]
Hola!
Ese problema es un bug que tiene la versión actual del mod pero será actualizado en unos días, igual que otros mods, si no deseas esperar, puedes descargar manualmente el mod y ponerlo dentro de tu carpeta "mods", no te olvides de borrar la versión que actualmente te da problemas.
Por cierto este no es un problema de MultiMinecraft, es del modpack Mundo Wigetta.
