### ISSUE TITLE
Aparicion de un extraño cuadro en medio del multiminecraft que no me deja ver las instancias ni seleccionarlas v2.6.8.2

### ISSUE THREAD

**Issue by alexjandro8** [HeberonYT/MultiMinecraft#15]
Hola, por culpa de este maldito cuadro, no me deja ver nada ni hacer nada!!!, Es la ultima version y la he reinstalado y he hecho de todo

FOTO: https://gyazo.com/3b9a194ec8489f602747d7e5fd87282c

**Comment by HeberonYT** [comment]
Es la primera vez que me reportan este problema en esta versión, quizás sea incompatibilidad con tu sistema, pero voy a revisarlo y a actualizar la app.

**Comment by HeberonYT** [comment]
No pude replicar este error, pero ahora en MultiMinecraft Deluxe no está presente este problema.
