### ISSUE TITLE
Error de launcher nativo

### ISSUE THREAD

**Issue by Artuto** [HeberonYT/MultiMinecraft#17]
He creado una nueva instancia y al darle a PLAY se actualiza el launcher y salta este error 

https://artuto.s-ul.eu/hnfJZTRx

**Comment by HeberonYT** [comment]
Hola,
Parece que este problema está relacionado con el launcher Nuevo, prueba por favor seleccionando el launcher viejo en los ajustes de MultiMine, quizás sea algún fallo en una actualización del launcher original.

**Comment by Yael0013wars** [comment]
hola el problema que tengo es que multiminecraft me detecta como si tuviera un java de 32 bits y tengo el de 64 y cuando le doy en analizar sistema si me sale que tengo java 64 bits y pues no me deja poner mas de 2 memoria ram al minecraft

**Comment by HeberonYT** [comment]
no pude replicar este error, pero se ha actualizado la versión del lanzador Premium, quizás este solucionado ahora, de lo contrario volver a abrir ticket.
