### ISSUE TITLE
Configuración

### ISSUE THREAD

**Issue by Test83318** [HeberonYT/MultiMinecraft#2]
Al pulsar el botón para abrir la configuración
![fail_setup](https://user-images.githubusercontent.com/31696699/33805493-2aad5114-ddba-11e7-9714-1b0225e940e1.png)
Pulso en detalles.
https://pastebin.com/m3tPMLcp

**Comment by HeberonYT** [comment]
Primero quiero darte las gracias por añadir los detalles en pastebin, es mucho más fácil para leer.

Este problema aparece al abrir otra ventana? O solo en Ajustes?

Al parecer estás utilizando MultiMinecraft Normal, has intentado con la versión Deluxe? Podrías instalarla en la misma ubicación ya que no te pedirá licencia.

**Comment by Test83318** [comment]
Sip, solo me pasa con preferencias. Y en la versión Normal solo, por otro lado ayer me funcionaba correctamente

**Comment by HeberonYT** [comment]
Ok pues voy a revisar esta ventana para verificar cuál es el problema.

**Comment by HeberonYT** [comment]
Este problema continúa sucediendo?
o sucede aveces?

**Comment by Test83318** [comment]
Sigue fallando

**Comment by HeberonYT** [comment]
Ok, trataré de solucionarlo en la siguiente actualización, de momento te recomiendo instalar la versión Deluxe para que hagas uso de la aplicación.

**Comment by Test83318** [comment]
Muchas gracias
