### ISSUE TITLE
problemas con java 64 

### ISSUE THREAD

**Issue by Yael0013wars** [HeberonYT/MultiMinecraft#20]
El problema que tengo es que multiminecraft me detecta java 32 bits cuando tengo el de 64 y no m deja asignar mas memoria ram

**Comment by CanterV56** [comment]
Yo tenia el mismo problema pero ya lo solucione espero que te sirva a ti también 
1. Desinstalar las o la versión de java con la herramienta o manualmente
https://www.java.com/es/download/uninstalltool.jsp
2.Instalar la versión de java para 64 bits (Aquí estaba el problema ya que había instalado la primera opción y esta era para 32 bits)
![anotacion 2019-01-02 220642](https://user-images.githubusercontent.com/46335340/50622433-0bcb2480-0edb-11e9-8f42-d56ba7ef0f48.jpg)

**Comment by HeberonYT** [comment]
hola, @Yael0013wars para solucionar este problema debes eliminar la instalación de java de 32 bits, posiblemente tengas también la de 64 pero tu versión principal la detecta como 32, así que eliminala desde el panel de control y verifica que conserves la versión de 64 bits, si no la tienes entonces puedes bajarla desde la pagina que te ha deja @CanterV56 .

Saludos!
