### ISSUE TITLE
Problema al añadir una carpeta .minecraft

### ISSUE THREAD

**Issue by CanterV56** [HeberonYT/MultiMinecraft#21]
Hola espero que estén muy bien mi problema es el siguiente: 
Mi versión del multiminecraft classic edition es la versión 2.7.0.0 y en esta actualización se implemento la opción De arrastrar y soltar en la pestaña de añadir una carpeta .minecraft y aquí esta mi problema y es que a la hora de añadir una carpeta no me deja :'(

**Comment by HeberonYT** [comment]
Hola, debes explicar el problema o error que tengas. Si es con imágenes mejor.
También explica los pasos que realizaste para intentar replicar el error en mi aplicación.

**Comment by CanterV56** [comment]
Hola muchas gracias por responder :D 
Pero ya lo solucione Reinstalando el programa
