### ISSUE TITLE
Detección de virus al descargar

### ISSUE THREAD

**Issue by medalog** [HeberonYT/MultiMinecraft#22]
Buenas, he intentado realizar la descarga pero me dice que tiene un virus. No tengo idea de que lo pasa, uso Windows defender y es la primera vez que me pasa esto. 

![59b2c538ba37dec590e28c2ef56e6df1](https://user-images.githubusercontent.com/30416322/51009520-35b1c600-152f-11e9-9241-d41af5a2725f.png)

**Comment by HeberonYT** [comment]
hola, gracias por tu aviso.

Esto es un falso positivo, en ocasiones nuestras aplicaciones son detectadas como maliciosas debido a ciertas partes del código o al comportamiento de la misma, pero no significa que lo sea o que este infectada, voy a resolver esto en próximas versiones.
De momento puedes seguir utilizándola desactivando la detección de virus de tu antivirus o en la configuración de Google chrome.
