### ISSUE TITLE
Bug en la versión Optifine 1.13.2 (Sin Sonido)

### ISSUE THREAD

**Issue by luismafla17** [HeberonYT/MultiMinecraft#23]
Hola, sucede que cuando creo una instancia con la versión optifine 1.13.2 ésta se crea sin sonido, probé creando una con la versión normal de 1.13.2 (sin optifine) y el sonido va perfectamente.
Intenté dando F3 + T para recargar los recursos pero no funciona.

[https://pastebin.com/wNL0TWcM](url)

**Comment by HeberonYT** [comment]
Gracias por el reporte, voy a revisarlo y regresaré con una solución.
