### ISSUE TITLE
Bug "No se estableció conexion con el servidor"

### ISSUE THREAD

**Issue by TermiSenpai** [HeberonYT/MultiMinecraft#24]
Despues de instalar un modpack con un launcher oficial de Heberon, todas las carpetas que tenia con anterioridad dejaron de visualizarse y solo me salia la del modpack, aunque en la carpeta aun tenia todas, despues de reinstalar y volver a instalar (salvando todas las carpetas anteriores al modpack) me salia el error de "No se estableció conexion con el servidor", he probado a reinicar el pc, el router, desactivar el firewall... pero no hubo suerte. 
![screenshot_1](https://user-images.githubusercontent.com/46727850/51209822-78014b80-1911-11e9-8f91-7ccbf82b1b14.png)

**Comment by TermiSenpai** [comment]
Capturas adicionales: 
![screenshot_2](https://user-images.githubusercontent.com/46727850/51210931-52c20c80-1914-11e9-9009-1a45d69ae53f.png)
![screenshot_3](https://user-images.githubusercontent.com/46727850/51210954-640b1900-1914-11e9-872c-ab4fd8f458ea.png)

Nunca llega a empezar la descarga
![screenshot_4](https://user-images.githubusercontent.com/46727850/51210996-7e44f700-1914-11e9-8aeb-6dc70f57219b.png)

![screenshot_5](https://user-images.githubusercontent.com/46727850/51211204-2490fc80-1915-11e9-9cef-153430a54d32.png)

**Comment by liobarrios** [comment]
Does the same thing happen to me as I solve it?

**Comment by liobarrios** [comment]
me pasa lo mismo como lo soluciono ?

**Comment by TermiSenpai** [comment]
> me pasa lo mismo como lo soluciono ?

Todavia no encontré la manera, tampoco se que lo causa, pero espero que sea solucionable

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte.
Este error ya fue solucionado, solo debes iniciar tu aplicación y te aparecerá un mensaje de una nueva versión, acéptala para que se instale.

Saludos!

**Comment by belce6** [comment]
Me salta el mismo error con el modpack Planeta Vegeta 7
![1](https://user-images.githubusercontent.com/62276631/76825363-82122900-67f8-11ea-91ff-324b9a4a77ac.png)
![2](https://user-images.githubusercontent.com/62276631/76825364-83435600-67f8-11ea-83b3-3ca98debc77a.png)
