### ISSUE TITLE
Error "No se relaciona con el servidor"

### ISSUE THREAD

**Issue by liobarrios** [HeberonYT/MultiMinecraft#25]
![51209822-78014b80-1911-11e9-8f91-7ccbf82b1b14](https://user-images.githubusercontent.com/46746371/51244650-58474300-1964-11e9-88f6-fdb07a69f76f.png)
 como lo soluciono ? 
Does the same thing happen to me as I solve it?

**Comment by liobarrios** [comment]
como lo soluciono

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte.
Este error ya fue solucionado, solo debes iniciar tu aplicación y te aparecerá un mensaje de una nueva versión, acéptala para que se instale.

Saludos!

**Comment by liobarrios** [comment]
gracias saludosEnviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: HeberonYT <notifications@github.com> Fecha: 17/1/19  22:17  (GMT-03:00) A: HeberonYT/MultiMinecraft <MultiMinecraft@noreply.github.com> CC: liobarrios <leonelgamer499@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [HeberonYT/MultiMinecraft] Error "No se relaciona con el servidor" (#25) Hola, gracias por tu reporte.

Este error ya fue solucionado, solo debes iniciar tu aplicación y te aparecerá un mensaje de una nueva versión, acéptala para que se instale.

Saludos!



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HeberonYT/MultiMinecraft","title":"HeberonYT/MultiMinecraft","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/HeberonYT/MultiMinecraft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HeberonYT in #25: Hola, gracias por tu reporte.\r\nEste error ya fue solucionado, solo debes iniciar tu aplicación y te aparecerá un mensaje de una nueva versión, acéptala para que se instale.\r\n\r\nSaludos!"}],"action":{"name":"View Issue","url":"https://github.com/HeberonYT/MultiMinecraft/issues/25#issuecomment-455392162"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/HeberonYT/MultiMinecraft/issues/25#issuecomment-455392162",

"url": "https://github.com/HeberonYT/MultiMinecraft/issues/25#issuecomment-455392162",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
