### ISSUE TITLE
Fallo no conecta con el servidor.

### ISSUE THREAD

**Issue by oniricoh** [HeberonYT/MultiMinecraft#26]
Acabo de instalar el  multiminecraft, y al abrirlo me sale un error que dice que no pudo establecer coneccion con el servidor, probe desactivando el antivirus y abriendo como administrador y nada no va, intento crear una carpeta y se queda trabada no descarga nada....no se como agrego mi cuenta de minecraft? no veo ninguna opcion por ningun lado, como sabe este programa donde tengo instalado mi minecraft, no entiendo nada.

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte.
El error ya fue solucionado, solo abre tu aplicación MultiMinecraft y acepta la actualización para que te ponga la ultima versión.

Para saber cual es el funcionamiento de MultiMinecraft por favor revisa todos los vídeos sobre esta aplicación disponibles en mi canal.
