### ISSUE TITLE
Problema con crear una carpeta con forge

### ISSUE THREAD

**Issue by clonem95** [HeberonYT/MultiMinecraft#27]
![1](https://user-images.githubusercontent.com/47951453/53304286-62047600-3841-11e9-9511-508ffca35aef.png)
esto es lo que me aparece cada vez que intento hacer una carpeta con forge que puedo hacer para solucionarlo

**Comment by HeberonYT** [comment]
Este problema está resuelto en la versión 2.7.1.
Por favor actualiza a esa versión.
Saludos!
