### ISSUE TITLE
Error en la descripción de las instancias en la versión deluxe

### ISSUE THREAD

**Issue by PabloGirol** [HeberonYT/MultiMinecraft#28]
Tengo dos carpetas: una con mods y una para usar en minecraft premium... Pero al seleccionar el apartado de detalles siempre aparece lo mismo
![error forge](https://user-images.githubusercontent.com/47150336/54085004-f4744180-4338-11e9-8d65-403819acea8b.jpg)
Esta, No tiene forge instalado....
![error forge1](https://user-images.githubusercontent.com/47150336/54085013-0c4bc580-4339-11e9-832d-fab426310caf.jpg)
Esta, Tiene forge pero en la versión 1.7.10 y un perfil con optifine en la 1.12.2
Por si hace falta, es la ultima versión de MM2

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte.
Lo he revisado y tengo el mismo problema que tú, lo voy a solucionar en la siguiente actualización.

**Comment by HeberonYT** [comment]
Ya fue solucionado en la versión 2.7.2
