### ISSUE TITLE
problema al abrir multiminecraft

### ISSUE THREAD

**Issue by clonem95** [HeberonYT/MultiMinecraft#29]
![minecraft](https://user-images.githubusercontent.com/47951453/54399471-92933f00-468c-11e9-9b8a-72b64461cc88.png)
 cada ves que intento abrir el multiminecraft sale esto

**Comment by HeberonYT** [comment]
Hola, parece ser un problema al descargar la actualización, añadiré mas opciones para que la aplicación pruebe a descargar desde varios lugares

**Comment by HeberonYT** [comment]
Solucionado en nuevas versiones.
