### ISSUE TITLE
ModPack no arranca.

### ISSUE THREAD

**Issue by Cashiiel** [HeberonYT/MultiMinecraft#3]
Hola Hebe, muchas gracias por volver con todo con tus modpacks. Soy usuario de MC premium y no puedo iniciar el modpack con la herramienta MultiMinecraft 2.
Subí la ram desde las opciones de la aplicación como del launcher.

Qué puede estar sucediendo? (adjunto mensajes de error)

Mensaje de error al no modificar la ram:
"Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release"

Mensaje al modificar la ram desde la herramienta y launcher:
"Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size."

De antemano gracias!!!﻿

PD: Antes me había pasado algo parecido y lo iniciaba manual (sin herramienta).

**Comment by Cashiiel** [comment]
Solucionado!!!

Actualice Java y use la configuración de la herramienta de “Launcher Premium Nuevo (.exe)”, arranco sin ningún problema, muchas gracias y perdón por malgastar tu tiempo.

Abrazo y sigue trabajando así de bien C:

**Comment by HeberonYT** [comment]
Hola
Estoy casi seguro que ese problema es causado por la versión de Java que tienes instalado en tu ordenador, seguramente tienes Java de 32 bits.
Una de las limitaciones de la versión de 32bits es que no se puede asignar más de 1gb.
Debes quitar esa versión e instalar Java de 64bits
