### ISSUE TITLE
The error is: Font 'Lucida Sans' does not support style 'Regular'

### ISSUE THREAD

**Issue by JoilerDGT** [HeberonYT/MultiMinecraft#30]
Al abrir el launcher sale este error:
![Problema](https://user-images.githubusercontent.com/49568679/56056510-007d6580-5d22-11e9-8456-06785a747ee6.png)

**Comment by HeberonYT** [comment]
hola,
por favor intenta descargar e instalar el tipo de letra, puedes bajarla aquí:
http://www.911fonts.com/font-download/download_LucidaSansRegular_5897.htm

Después de instalar la fuente, reinicia tu ordenador y vuelve a abrir la aplicación.
Informame si se soluciona tu problema, saludos.

**Comment by JoilerDGT** [comment]
Esta solucionado, muchas gracias por la ayuda.

**Comment by HeberonYT** [comment]
perfecto, gracias por avisar.
