### ISSUE TITLE
Problema al Ejecutar Sk launcher 

### ISSUE THREAD

**Issue by GianManu364** [HeberonYT/MultiMinecraft#31]
intento abrir el sk launcher ".jar" o ".exe" y ninguno de los dos abre me manda a la pagina oficial del launcher

**Comment by HeberonYT** [comment]
He actualizado los lanzadores. Pro varo abre tu aplicación y se descargarán automáticamente los lanzadores, tambien puedes hacerlo manualmente en Ajustes/Minecraft/Actualizar todos los lanzadores.
