### ISSUE TITLE
Virus trollano

### ISSUE THREAD

**Issue by lmentrix2** [HeberonYT/MultiMinecraft#32]
Cuando Va esta en updater mi antivirus me detecta un virus trollano el archivo es Updater.zip hay donde se encontro un virus

**Comment by HeberonYT** [comment]
hola, este tipo de notificaciones son un "falso positivo", es decir que no se incluye ningún virus pero es catalogado como tal debido a los procedimientos o características del programa.
Que antivirus utilizas?
