### ISSUE TITLE
Error de modganeger

### ISSUE THREAD

**Issue by Wonw123** [HeberonYT/MultiMinecraft#33]
cuando me meto a modmanger para instalar un mod me apare un error Referencia a objeto no establecida como intalacion de un objeto. error en TileView1.click

**Comment by dead616** [comment]
A mi igual me aparece este error, adjunto una imagen para mostrarlo.
![modmanagererror](https://user-images.githubusercontent.com/51055580/58384302-fdb69700-7f94-11e9-8752-a479f6c06772.png)

**Comment by HeberonYT** [comment]
Este error lo he solucionado con la nueva actualización 2.7.4.1 que ya esta disponible.
