### ISSUE TITLE
acceso denegado a la ruta

### ISSUE THREAD

**Issue by Wonw123** [HeberonYT/MultiMinecraft#35]
no se por que me das este erro a intalar un modpack nuevo. 
![Captura de pantalla (21)](https://user-images.githubusercontent.com/51055387/58448960-32c70480-80cf-11e9-8876-a1c9cc77e21c.png)

**Comment by HeberonYT** [comment]
Gracias por tu reporte, voy a investigar la causa del problema.

**Comment by HeberonYT** [comment]
Te comento que este error se muestra solo en algunos Modpacks de ProjectLauncher, será resuelto en los próximos días cuando veas nuevos modpacks en esa lista.

**Comment by Fortras** [comment]
Cuando seria solucionado el problema aproximadamente??

**Comment by GuerreroCraft61** [comment]
A mi me pasa estas dos cosas, creo que estan relacionados
![Captura1](https://user-images.githubusercontent.com/30746531/65625292-d23bcb80-dfcb-11e9-87c9-ee6081fa523c.png)
![Captura2](https://user-images.githubusercontent.com/30746531/65625294-d23bcb80-dfcb-11e9-9964-a6319ddb66da.PNG)

**Comment by HeberonYT** [comment]
Será solucionado en la versión 2.8.1
