### ISSUE TITLE
Solo música

### ISSUE THREAD

**Issue by Conan26062001** [HeberonYT/MultiMinecraft#36]
Hola,
Cuando abro cualquier lanzador no premium, ya sea .exe o .jar se inicia y solo se escucha la música no se carga el juego, además cuando le das para ver la ventana del juego no sale nada, es como si fuera transparente el juego.
Muchas gracias por la ayuda.

**Comment by HeberonYT** [comment]
Hola, este tipo de problemas no esta relacionado con MultiMinecraft, ya que mi aplicación termina de realizar sus funciones cuando tu inicias una instancia y se ejecuta el lanzador de Minecraft seleccionado.

Lo que ocurra después de abrirse el lanzador, no depende de MultiMinecraft, y si tuvieras algún error podría deberse a tu Java, los gráficos de tu PC, la memoria ram, etc.

En tal caso deberías informar sobre este problema a un desarrollador del lanzador que no se vea.

**Comment by Conan26062001** [comment]
Vale, muchas gracias por la ayuda.
