### ISSUE TITLE
No inicia TLauncher

### ISSUE THREAD

**Issue by RubizZ** [HeberonYT/MultiMinecraft#37]
Cuando añado el Custom Launcher (el .exe) y lo doy a PLAY, se cierra el MultiMinecraft y no abre el launcher. No quiero usar ningun otro porque este te permite usar skins creando una cuenta en su pagina. Estaría bien que lo añadieras a los Launcher predeterminados de MultiMinecraft o que me ayudaras a solucionar este bug. Gracias

**Comment by HeberonYT** [comment]
Gracias por tu reporte.
He identificado y solucionado el problema que impedía iniciar el CustomLauncher, asi que en la próxima actualización de MultiMinecraft ya funcionará.

Respecto al "TLauncher", no es compatible con el archivo de perfiles que se crea con el launcher original, por ese motivo, cada vez que inicies el TLauncher deberás seleccionar la versión de minecraft que deseas ejecutar, tal como lo muestro a continuación.
![Screenshot_10](https://user-images.githubusercontent.com/13698597/60847320-e67be380-a1a7-11e9-89c5-5974d7af8959.png)

**Comment by HeberonYT** [comment]
Por cierto, para agregar el TLauncher debes descargar desde su página oficial la edición para Mac, dentro del .zip que se bajará encontrarás el lanzador en formato .jar, ese archivo debes agregarlo a MultiMinecraft como lanzador Custom.

**Comment by RubizZ** [comment]
Entiendo, pero entonces en siempre que lo inicie con TLauncher saldrá la versión en blanco pero podre usar las que están predeterminadas para descargar? O solo las que añadas manualmente? Ya vi que en la version de MAC esta el .jar, supongo que no funcionará con el .exe, pero de todas formas muchas gracias por todo

**Comment by RubizZ** [comment]
Y otra cosa, cuando sacaras la versión en la que estará arreglado todo esto?

**Comment by HeberonYT** [comment]
@RubizZ la actualización de MultiMinecraft ya fue liberada, solo inicia tu aplicación y se actualizará.
Si no lo hace, siempre puedes actualizarlo de forma manual descargando el setup desde la web de MultiM.

Cuando crees una instancia, la primera vez que ejecutes TLauncher no estará seleccionada la versión en el perfil del lanzador, pero tu puedes seleccionarla en la lista desplegable como mostré en la imagen anterior.
Eso solo pasará en la primera vez, porque en las siguientes veces ya guardará el perfil que tu seleccionaste manualmente.

**Comment by HeberonYT** [comment]
@RubizZ y tienes razon, el lanzador en formato .exe no funcionará porque si te fijas es un instalador.
En cambio el formato .jar Si es el lanzador, por eso debes descargarlo en ese formato.

**Comment by RubizZ** [comment]
Si que funciona el .exe, el que te descargas es un instalador, pero cuando lo inicias, se te crea el .exe launcher en .minecraft y ese si funciona
