### ISSUE TITLE
Fallo en la carpeta ¨Descargar Mods¨

### ISSUE THREAD

**Issue by FaZeDavidDC** [HeberonYT/MultiMinecraft#38]
Cuando abres la opción ¨Descargar Mods¨  aparece este error ¨Error en el servidor remoto: [410] desaparecido por favor reporta este error¨ y no aparecen Mods

**Comment by HeberonYT** [comment]
Gracias por tu reporte.
Efectivamente parece que se cambio la DB de Curse, por lo tanto voy a actualizar al mismo formato

**Comment by HeberonYT** [comment]
Estoy trabajando para resolverlo, pero tomará un tiempo porque debo escribir básicamente todo el código que maneja este proceso.

**Comment by HeberonYT** [comment]
Solucionado, pueden ocupar ModManager en la versión 2.9.1 que se libera el día 14 de septiembre 2020.
