### ISSUE TITLE
Fallo cargando texture packs

### ISSUE THREAD

**Issue by rgmengual99** [HeberonYT/MultiMinecraft#39]
Lanza error al cargar los texture packs de una .minecraft añadida a multiminecraft.
Pinta que es por la cantidad, tenía muchos resource packs.

![imagen](https://user-images.githubusercontent.com/53658465/62414397-fbb72700-b61a-11e9-8b1e-5026f1514369.png)

TEXTO COMPLETO DEL ERROR:

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en MultiMinecraft_2___Premium.FormOpInsta.c(Object A_0, RunWorkerCompletedEventArgs A_1)
   en System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by HeberonYT** [comment]
Este error será solucionado en la actualización 2.8.1
