### ISSUE TITLE
Configuraciones no Abre

### ISSUE THREAD

**Issue by DJDavidRamos** [HeberonYT/MultiMinecraft#40]
Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.InvalidOperationException: Error al crear el formulario. Consulte Exception.InnerException para obtener más detalles. Error: Un componente externo produjo una excepción. ---> System.Runtime.InteropServices.SEHException: Un componente externo produjo una excepción.
   en System.Buffer.__Memmove(Byte* dest, Byte* src, UInt64 len)
   en System.Buffer._Memmove(Byte* dest, Byte* src, UInt64 len)
   en System.Buffer.Memmove(Byte* dest, Byte* src, UInt64 len)
   en System.Buffer.Memcpy(Byte[] dest, Int32 destIndex, Byte* src, Int32 srcIndex, Int32 len)
   en System.IO.UnmanagedMemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   en System.IO.BinaryReader.ReadBytes(Int32 count)
   en System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArrayAsBytes(ParseRecord pr)
   en System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(BinaryHeaderEnum binaryHeaderEnum)
   en System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   en System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   en MultiMinecraft_2___Premium.My.Resources.Resources.a1()
   en MultiMinecraft_2___Premium.FormAjustes.cd()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en c.a.as[a](a A_0)
   en MultiMinecraft_2___Premium.Form1.m(Object A_0, ItemClickEventArgs A_1)
   en DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   en DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   en DevExpress.XtraBars.BarItemLink.OnLinkClick()
   en DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   en DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   en DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   en DevExpress.XtraBars.Controls.CustomLinksControl.OnMouseUp(MouseEventArgs e)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en DevExpress.XtraBars.Controls.DockedBarControl.WndProc(Message& msg)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3416.0 built by: NET472REL1LAST_B
    Código base: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMinecraft 2 - Premium
    Versión del ensamblado: 2.8.0.0
    Versión Win32: 2.8.0.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/MultiMinecraft%202%20-%20DELUXE.exe
----------------------------------------
Microsoft.VisualBasic
    Versión del ensamblado: 10.0.0.0
    Versión Win32: 14.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3416.0 built by: NET472REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3429.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3324.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
DevExpress.BonusSkins.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.BonusSkins.v18.1.DLL
----------------------------------------
DevExpress.Utils.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.Utils.v18.1.DLL
----------------------------------------
DevExpress.Data.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.Data.v18.1.DLL
----------------------------------------
DevExpress.XtraEditors.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.XtraEditors.v18.1.DLL
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
MySql.Data
    Versión del ensamblado: 6.9.10.0
    Versión Win32: 6.9.10.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/MySql.Data.DLL
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3260.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3221.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
DevExpress.XtraBars.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.XtraBars.v18.1.DLL
----------------------------------------
DevExpress.XtraRichEdit.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.XtraRichEdit.v18.1.DLL
----------------------------------------
DevExpress.XtraLayout.v18.1
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.XtraLayout.v18.1.DLL
----------------------------------------
DevExpress.RichEdit.v18.1.Core
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.RichEdit.v18.1.Core.DLL
----------------------------------------
DevExpress.Office.v18.1.Core
    Versión del ensamblado: 18.1.6.0
    Versión Win32: 18.1.6.0
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/DevExpress.Office.v18.1.Core.DLL
----------------------------------------
System.ComponentModel.DataAnnotations
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Xaml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3429.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versión del ensamblado: 0.0.0.0
    Versión Win32: 4.7.3416.0 built by: NET472REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 7.0.0.0
    Versión Win32: 7.0.1.18622
    Código base: file:///C:/Users/Edwin%20Ramos/AppData/Roaming/MC/MultiMinecraft2/Newtonsoft.Json.DLL
----------------------------------------
System.EnterpriseServices
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
UIAutomationClient
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3429.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
System.Management
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3440.0 built by: NET472REL1LAST_B
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.VisualBasic.resources
    Versión del ensamblado: 10.0.0.0
    Versión Win32: 14.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic.resources/v4.0_10.0.0.0_es_b03f5f7f11d50a3a/Microsoft.VisualBasic.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by HeberonYT** [comment]
@DJDavidRamos por favor, sube tu archivo de configuración para revisar la causa.
Esta localizado en la carpeta de instalacion de **MultiMinecraft/settingsMM2.conf**

**Comment by HeberonYT** [comment]
Sin respuesta.
