### ISSUE TITLE
Error al ejecutar el lanzador

### ISSUE THREAD

**Issue by GuerreroCraft61** [HeberonYT/MultiMinecraft#41]
![Captura1](https://user-images.githubusercontent.com/30746531/65626494-cd781700-dfcd-11e9-9d3a-ca2ef078d394.png)

**Comment by GuerreroCraft61** [comment]
mmm...????
PD: Uso win 10

**Comment by dpManuqb** [comment]
También me pasa. Me funcionaba hasta que de repente me salió eso o que no era capaz de conectarse a ninguno de los 2 servidores de descarga. Y cuando consigo abrir el lanzador premium nuevo se para y me sale: "Unable to update the Minecraft Runtime Environment"

**Comment by Yael0013wars** [comment]
Yo lo reinstale y me sirvió por unos minutos y me volvió a dar el fallo

**Comment by GuerreroCraft61** [comment]
No hace falta reinstalarlo, con que lo inicies como administrador o actualizar launcher, de vez en cuando funciona

**Comment by dpManuqb** [comment]
Queremos soluciones, no remedios!

**Comment by GuerreroCraft61** [comment]
Y que quieres que te diga :v, hablas como si yo fuera developer de MultiMinecraft o algo, solo lo digo para ayudar sabes, Heberon no dice nada y tampoco lo soluciona

**Comment by DDONALDD** [comment]
Heberon ya está trabajando en la próxima actualización dónde seguro ya estará resuelto el problema...

**Comment by HeberonYT** [comment]
Gracias por sus reportes, eso se debia a problemas con las descargas desde los host.
Ya está solucionado, lo he comprobado ahora mismo.
