### ISSUE TITLE
Error "Cannot Read That as a zip file"

### ISSUE THREAD

**Issue by Jocando21** [HeberonYT/MultiMinecraft#42]
Cuando quiero descargar un modpack me presenta esta ventana.
![image](https://user-images.githubusercontent.com/55963038/65840965-5f409680-e2e4-11e9-875a-70dc16bd25be.png)

**Comment by HeberonYT** [comment]
Estos problemas ya están solucionados en su mayoría, solo queda solucionar al descargar un modpack desde ProjectLauncher, para ello recibirás una actualización en los siguientes días.

**Comment by HeberonYT** [comment]
Se solucionará en la versión 2.8.1
