### ISSUE TITLE
AYUDA PLS !!!! MULTIPLES ERRORES !!!!

### ISSUE THREAD

**Issue by GamaG27** [HeberonYT/MultiMinecraft#43]
HOLA
recientemente me instale el multiminecraft y me aparecio esta advertecia al intentar instalar modpacks y/o crear una incidencia con optifine

![65840965-5f409680-e2e4-11e9-875a-70dc16bd25be](https://user-images.githubusercontent.com/56368966/66520856-db578d00-eae1-11e9-8223-fc6b675f854c.png)

 y otra situacion que aparecio es al crear una instancia con forge el launcher (SHIGINIMA y/o SK launcher)  se pone a descagar algo para cuando acaba le doy play  para hacer el mismo proceso otra vez ess un circulo vicioso

**Comment by Dorian-97** [comment]
me pasa lo mismo

**Comment by HeberonYT** [comment]
Estos problemas ya están solucionados en su mayoría, solo queda solucionar al descargar un modpack desde ProjectLauncher, para ello recibirás una actualización en los siguientes días.

**Comment by HeberonYT** [comment]
Será solucionado en la versión 2.8.1
