### ISSUE TITLE
Prohibido el acceso

### ISSUE THREAD

**Issue by Zulu12** [HeberonYT/MultiMinecraft#44]
Hola,

Me da una error al de prohibido intentar comprobar los mods

![2019-10-13 (3)](https://user-images.githubusercontent.com/11544284/66711869-403a0e00-ed94-11e9-8503-a8edd21f4b75.png)

**Comment by HeberonYT** [comment]
Hola, he visto este problema y espero solucionarlo muy pronto, por favor espera la siguiente actualización.

**Comment by HeberonYT** [comment]
Estoy trabajando para resolverlo, pero tomará un tiempo porque debo escribir básicamente todo el código que maneja este proceso.

Mantendré solo un ticket abierto sobre este tema. Las novedades las escribiré en #38
