### ISSUE TITLE
No me deja arrancar niguna version de minecraft en Multiminecraft 

### ISSUE THREAD

**Issue by Yarayarag** [HeberonYT/MultiMinecraft#46]
Puedo crear instancias pero no ejecutarlas ya que me aparece la siguiente leyenda "unable to update the minecraft runtime environment" soy usuario premium de minecraft y quisiera serlo tambien de multiminecraft pero no puedo ejecutar las instancias creadas ya sea de vanilla o alguna con forge no me deja hacerlo de ninguna forma agradecería pudieras ayudarme

**Comment by HeberonYT** [comment]
Ve a los ajustes de MultiMinecraft y prueba cambiar el Launcher de Minecraft, te recomiendo usar el "**Premium Nuevo**" o el "**Premium Viejo Jar**"
