### ISSUE TITLE
Hace días que no establece conexión con los servidores

### ISSUE THREAD

**Issue by Schope034** [HeberonYT/MultiMinecraft#47]
Ya llevo días experimentando que no establece conexión con los servidores, y ademas cuando intento ejecutar una instancia me aparece un error diciendo diciendo "el ejecutable especificado no es una opción valida para esta plataforma de sistema operativo", que se hace aquí
![Sin títulogf](https://user-images.githubusercontent.com/56783079/67155729-1e7fe000-f2da-11e9-9553-933248c61aef.jpg)
?

**Comment by HeberonYT** [comment]
Hola, el mensaje "No se estableció conexión con los servidores" en qué momento ocurre?
Haces algo en especial para que aparezca ese mensaje?

**Comment by Schope034** [comment]
> Hola, el mensaje "No se estableció conexión con los servidores" en qué momento ocurre? Haces algo en especial para que aparezca ese mensaje?

Parece que ya esta resuelto, pero realmente no lo hacia, el mensaje aparecía al abrir la aplicación, actualizaba los launchers y al final aparecía ese mensaje.

**Comment by HeberonYT** [comment]
Entonces era un problema con las descargas del host, recientemente hice cambios para solucionarlo así que por favor vuelve a repórtalo si ocurre nuevamente.
