### ISSUE TITLE
error al intentas descargar mods

### ISSUE THREAD

**Issue by FranJavier99** [HeberonYT/MultiMinecraft#49]
sale un cartel
el titulo de cartel dice "Error en BW1.DoWork"
y el mensaje dice "Error en el servidor remoto: (403) Prohibido.
Por favor reporta este error."
por favor me descargue el MultiMinecraft por primera vez hace tiempo y antes no me había dado ningún error. Gracias

**Comment by Cyret** [comment]
Sigue sin solucionarse...

**Comment by HeberonYT** [comment]
Estoy trabajando para resolverlo, pero tomará un tiempo porque debo escribir básicamente todo el código que maneja este proceso.
Duplicado de #38
