### ISSUE TITLE
Carpetas fuera de lugar

### ISSUE THREAD

**Issue by CallmeGemini** [HeberonYT/MultiMinecraft#5]
Hola Heberon.
Esto no parece importante, pero son pequeños detalles... He creado la cuenta sólo para informar, así que espero no estar haciéndote perder tiempo.
Como ves se generan carpetas dentro de cada instancia, pero fuera de la carpeta .minecraft
Como con el juego "original" en Vanilla no pasa, supongo que la carpeta debería ir dentro de .minecraft o si es temporal ser eliminada ya que está vacía.
![carpetasvacias](https://user-images.githubusercontent.com/34552797/34010533-6b65f5f2-e10d-11e7-9601-13961e792183.jpg)

**Comment by HeberonYT** [comment]
Gracias por el informe, al parecer esa carpeta la crea el launcher de Minecraft, no contiene datos de la instancia, solo es para el sistema.
