### ISSUE TITLE
No puedo iniciar los mod pakcs 

### ISSUE THREAD

**Issue by aurebelca** [HeberonYT/MultiMinecraft#52]
descarge el modpack de planeta vegetta 7 y me dice esto cuando quiero jugar
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by HeberonYT** [comment]
Eso significa que tienes asignado 2GB de ram en el perfil del modpack de Planeta Vegetta, pero tu ordenador no puede asignar esa cantidad al juego.
Existen dos razones:
- Tu pc no tiene 2GB de ram
- Tienes instalado Java de 32 bits, debes quitarlo e instalar Java de 64bits.

**Comment by aurebelca** [comment]
Qué tal, ya arregle el problema gracias!!!
Pero ahora descárgate varios mods de karmaland y tengo el problem que el horno solo produce de uno en uno 😅😅
