### ISSUE TITLE
no puedo instalar ni hacer una instancia con forge

### ISSUE THREAD

**Issue by clonem95** [HeberonYT/MultiMinecraft#53]
cada vez que intento instalar el forge sea la versión que sea de minecraft me aparece este aviso: "failed to run processor: java.lang.RuntimeException:Failed to download realms jar see log for more details." que es lo que pasa y como puedo solucionarlo?

**Comment by HeberonYT** [comment]
Eso debe ser un problema con el instalador de Forge que no puede descargar algunas librerías, porque ahora mismo yo lo he probado desde MultiMinecraft y todo va bien.
