### ISSUE TITLE
Opción Descargar Mods fallo

### ISSUE THREAD

**Issue by Mrodas16** [HeberonYT/MultiMinecraft#57]
Al usar la opción de descargar un mod en cualquier instancia, se abre por menos de 1 segundo y luego desaparece y no deja usar el programa luego de desaparecer.
Saludos.

**Comment by Suigetsu52** [comment]
Tuve exactamente el mismo problema, yo pude capturar un video al respecto, parte del audio se perdió (debido a que mi PC no tiene mucha memoria y el procesador es algo viejo), pero en todo momento se ven los clics debido a los colores integrados en el mouse del video por el capturador. Ninguno de ellos tiene efecto, ya que el programa quedaba inútil exactamente después de usar el botón.
He de decir que no tengo ninguna licencia comprada actualmente, sigo corriendo los 15 días de prueba, no sé si ese dato sirva de algo, pero imagino que no está demás.

[proof-multiminecraft-mod-downloader.zip](https://github.com/HeberonYT/MultiMinecraft/files/4032165/proof-multiminecraft-mod-downloader.zip)

**Comment by Mrodas16** [comment]
@Suigetsu52  Eso mismo me pasa a mi, exactamente igual.

**Comment by Suigetsu52** [comment]
@Mrodas16 por lo que ví, un problema parecido fue reportado hace un tiempo ya, si no me equivoco en junio del año pasado, y @HeberonYT le respondió diciendo que "lo arreglaría, pero que tomaría tiempo porque debía reescribir el código por un problema" que si no me equivoco sonaba a compatibilidad, pero la versión 2.8.1 es la más reciente y es posterior a eso, de hecho, salió hace un mes, así que me imagino que habrá que esperar otra actualización o algo del estilo.

**Comment by Suigetsu52** [comment]
> @Mrodas16 por lo que ví, un problema parecido fue reportado hace un tiempo ya, si no me equivoco en junio del año pasado, y @HeberonYT le respondió diciendo que "lo arreglaría, pero que tomaría tiempo porque debía reescribir el código por un problema" que si no me equivoco sonaba a compatibilidad, pero la versión 2.8.1 es la más reciente y es posterior a eso, de hecho, salió hace un mes, así que me imagino que habrá que esperar otra actualización o algo del estilo.

Aquí hay una foto del otro reporte

![IMG_20200110_192925](https://user-images.githubusercontent.com/59622633/72193390-a6f4b500-33df-11ea-9310-0ace1f71e4aa.jpg)

**Comment by HeberonYT** [comment]
Duplicado de #38
