### ISSUE TITLE
Fallo al Actualizar

### ISSUE THREAD

**Issue by Strahum** [HeberonYT/MultiMinecraft#58]
Abro la aplicación de MultiMinecraft 2 - Deluxe Edition v2.8.1.0, comienza a actualizar y me da un error

[img]https://i.imgur.com/uiiWnyo.jpg[/img]

Le doy "Ok" y me sale un cartel que dice aplicando actualización, y me tira el siguiente error

[img]https://i.imgur.com/JfAKOTF.jpg[/img]

Le doy a "ok" nuevamente y se cierra.

**Comment by HeberonYT** [comment]
Realiza los siguientes pasos,
- abre la ubicación donde está instalada la aplicación.
- debes encontrar una carpeta llamada "updater" debes eliminarla por completo.
- vuelve a ejecutar MultiMinecraft.
________________________________

**Comment by HeberonYT** [comment]
He realizado cambios en la versión 2.8.3 para evitar futuros problemas relacionados con archivos existentes.
