### ISSUE TITLE
Cada vez que entro a la aplicación se pone a descargar el launcher

### ISSUE THREAD

**Issue by bitdeparidad** [HeberonYT/MultiMinecraft#59]
Cada vez que entro a la aplicacion descarga el launcher y si intento abrir el juego salta un error, lo que hace que tenga que esperar un rato para poder iniciar, esto sucede incluso habiendo pasado ni 2 minutos de haber abierto multiminecraft la ultima vez.

![image](https://user-images.githubusercontent.com/49416939/74036598-db4a9980-49bc-11ea-8111-c782624a6c75.png)

**Comment by HeberonYT** [comment]
Este problema debe estar solucionado en la versión 2.8.3
Si ocurre de nuevo en esa versión, por favor crea un nuevo ticket.
