### ISSUE TITLE
Ocurrio un problema al ejecutar el lanzador.  The specified executable is not a valid application for this OS platform Ayudenme porfavor!! Me pone ese error cuando abro una instancia en multiminecraft

### ISSUE THREAD

**Issue by Peeeeeeedro** [HeberonYT/MultiMinecraft#6]
Ocurrio un problema al ejecutar el lanzador.  The specified executable is not a valid application for this OS platform
Ayudenme porfavor!! Me pone ese error cuando abro una instancia en multiminecraft
Pls ayuden
https://pastebin.com/DLwcAYWG

**Comment by HeberonYT** [comment]
Hola Pedro, indícame los detalles de tu ordenador.
Windows:
Versión de Java:
MultiMinecraft:  ¿Deluxe o Normal?

**Comment by Peeeeeeedro** [comment]
Java 8 64 bits
Windows 7
Multiminwcraft Deluxe

El 18 dic. 2017 1:06 AM, "HeberonYT" <notifications@github.com> escribió:

Hola Pedro, indícame los detalles de tu ordenador.
Windows:
Versión de Java:
MultiMinecraft: ¿Deluxe o Normal?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/HeberonYT/MultiMinecraft/issues/6#issuecomment-352321070>,
or mute the thread

**Comment by Peeeeeeedro** [comment]
Java 7

**Comment by HeberonYT** [comment]
Tienes cuenta premium? 
Que lanzador estás utilizando?
Has probado con otro, intercambiando la versión .exe o .jar?
Mándame por favor una captura del error que te aparece.

**Comment by Peeeeeeedro** [comment]
Ya, ya lo solucione, igual gracias. Solo cambie a .jar lo tenia en el
launcher viejo .exe, pero ahora me anda. Gracias por la atencion.

**Comment by HeberonYT** [comment]
Ok solucionado, tema cerrado.

**Comment by Test83318** [comment]
@Peeeeeeedro Te importaría cerrar la issue

**Comment by crackgamer** [comment]
yo mi minecraft cuando lo abri se me quedo la pantalla en negro del minecraft

**Comment by crackgamer** [comment]
ya lo arregle yo
solo adios
