### ISSUE TITLE
Error de actualizacion (MM 2.8.0.0)

### ISSUE THREAD

**Issue by TheCiROMG** [HeberonYT/MultiMinecraft#62]
Al querer actualizar salta este error (QUE NO ES LA PRIMERA VEZ QUE ME SALTA), al querer actualizar otra versiones, tengo que dirigirme a la pagina y descargarla forzosamente

![1](https://user-images.githubusercontent.com/61605643/75594635-214cc780-5a68-11ea-9bcc-9d0dd522975b.png)
![2](https://user-images.githubusercontent.com/61605643/75594640-26117b80-5a68-11ea-8c71-7d19eabb5105.png)
![3](https://user-images.githubusercontent.com/61605643/75594646-29a50280-5a68-11ea-9a68-403277511de1.png)

**Comment by JowiiYT** [comment]
A mi me pasa exactamente lo mismo al actualizar me salta error, si alguien puede ayudarme a solucionarlo se lo agradecería.
Gracias

**Comment by HeberonYT** [comment]
Los usuarios que tengan mensajes de errores como los anteriores, deben actualizar MultiMinecraft de forma manual, descargando la ultima versión disponible en el sitio web oficial: https://heberon.com/multiminecraft/download

Hay 2 formas de actualizar manualmente:

Opción 1
Descargar el "Setup" de MultiMinecraft e instalarlo en la misma ruta donde tienen la versión vieja que les da problemas, de esta forma conservarán las instancias existentes y no perderán ninguna partida.

Opción 2
Descargar la ultima versión en formato ".zip". Solo deben extraer el contenido en la misma carpeta donde tienen la versión vieja que les da problemas, de esta forma conservarán las instancias existentes y no perderán ninguna partida.

Si la aplicación se actualiza de forma automática entonces ignora estas instrucciones.
