### ISSUE TITLE
ERROR O NO SÉ QUE HACER

### ISSUE THREAD

**Issue by EsdrasMujica** [HeberonYT/MultiMinecraft#64]
Buenas, tengo dos cosas y no se como arreglarlas:
La primera es que cuando ejecuto el MULTIMINECRAFT 2 v2.8 me sale no se estableció conexión con el Json de MultiMinecraft.
Y la segunda es que cuando voy a iniciar una instancia en el mismo programa me sale: 
Error code 001
Anulada la solicitud: No se puede crear un canal seguro SSL/TLS
![IMAGEN 1](https://user-images.githubusercontent.com/61911528/76145980-a5b1d280-6086-11ea-9c31-aa03261e38d1.png)
![IMAGEN 2](https://user-images.githubusercontent.com/61911528/76145981-a6e2ff80-6086-11ea-852e-e1369bd1fe80.png)

**Comment by eluqui** [comment]
buenas, estoy teniendo el mismo problema. Cuando le doy a +, Descargar mod pack me sale lo siguiente:
![problema](https://user-images.githubusercontent.com/61983079/76234032-dff6ad80-6207-11ea-9f73-eb3f084fc074.jpg)
 Nesecito ayuda.

**Comment by HeberonYT** [comment]
Resuelto, solo ejecuta la aplicación nuevamente.

El error que reporta @eluqui es diferente y será resuelto en una futura actualización.
