### ISSUE TITLE
Error "No se estableció conexión con el Json de Multiminecraft"

### ISSUE THREAD

**Issue by Nala1234** [HeberonYT/MultiMinecraft#65]
Hola. Tengo un problema y no sé qué hacer. Cada vez que inicio el Multiminecraft me sale "No se estableció conexión  con el Json de Multiminecraft. Inténtalo más tarde. He probado a lo largo de ayer y sigue saliéndome. Si alguien sabe cómo solucionarlo que me responda. Muchas gracias

**Comment by HeberonYT** [comment]
Resuelto, solo ejecuta la aplicación nuevamente.
