### ISSUE TITLE
No son visibles las descargas

### ISSUE THREAD

**Issue by charlyy97** [HeberonYT/MultiMinecraft#66]
Lleva como 2 horas descargando y aun no ha terminado, el no tener donde verlo aun frustra mas. Pongan donde poder verlo una pestaña o algo. Gracias
[http://prntscr.com/rdxmgm](url) @HeberonYT

**Comment by HeberonYT** [comment]
Hola, por favor agrega una captura donde pueda ver a lo que te refieres.

**Comment by charlyy97** [comment]
![imagen](https://user-images.githubusercontent.com/61994244/76458049-2ef43c80-63da-11ea-97a8-8b20ab782a98.png)
me da ese error

**Comment by HeberonYT** [comment]
Eso se debe a que no estas usando la ultima versión, debes descargar la ultima disponible desde el sitio oficial.

Cuando la descargues debes instalarla en la misma ruta donde tienes la versión vieja, o puedes extraer directamente el contenido del archivo .rar en la carpeta donde esta instalada la versión vieja.

![Screenshot_1](https://user-images.githubusercontent.com/13698597/88225904-e888d700-cc30-11ea-8848-e551afc8b02d.png)
