### ISSUE TITLE
Error code 001

### ISSUE THREAD

**Issue by Nelos36** [HeberonYT/MultiMinecraft#67]
![Captura](https://user-images.githubusercontent.com/57958060/76361514-7a95e000-631f-11ea-9d27-2516f459f4cc.PNG)

Constantemente me sale ese error. Si intento descargar mods, o en cuanto le doy al boton de play.

**Comment by HeberonYT** [comment]
Debes descargar la ultima versión disponible desde el sitio oficial.

https://heberon.com/multiminecraft/download
