### ISSUE TITLE
Ocurrio un problema al establecer la conexion

### ISSUE THREAD

**Issue by jasbi06** [HeberonYT/MultiMinecraft#68]
Cuando le doy a modpack para añadir alguno me sale un error de Ocurrio un problema al establecer la conexion Anulada solicitud: No se puede crear un canal seguro SSL/TLS
![error](https://user-images.githubusercontent.com/43568155/76425802-6ea33000-63aa-11ea-953d-7b1cf821f226.PNG)

**Comment by HeberonYT** [comment]
Debes descargar la ultima versión disponible desde el sitio oficial.

https://heberon.com/multiminecraft/download
