### ISSUE TITLE
error code:001

### ISSUE THREAD

**Issue by blacpoin** [HeberonYT/MultiMinecraft#69]
hola,me paso este error y quisiera saber como resolverlo
![Anotación 2020-03-11 202350](https://user-images.githubusercontent.com/62076541/76456937-2995f280-63d8-11ea-96df-2aa3ae90b93e.png)

**Comment by EsdrasMujica** [comment]
A mi tampoco me pasó y tampoco sé como resolverlo
![P22](https://user-images.githubusercontent.com/61911528/76554299-8c959100-648d-11ea-8bcc-7fd0f5789339.png)

**Comment by blacpoin** [comment]
pues a esperar a que nos respondan no tenemos otra

**Comment by HeberonYT** [comment]
Debes descargar la ultima versión disponible desde el sitio oficial.

https://heberon.com/multiminecraft/download
