### ISSUE TITLE
error de launcher 

### ISSUE THREAD

**Issue by DANIELXDXD** [HeberonYT/MultiMinecraft#7]
ayuda por favor quiero jugar pero cuando le doy jugar me manda al launcher y no cargan los perfiles y por lo tanto no me deja entrar, antes estaba bien pero ahora que se actualizo esto paso

**Comment by VigilantesG** [comment]
Lo mismo me sucede :v 
Es un bugs con los perfiles.. A espera que heberon lo solucione!...

**Comment by VigilantesG** [comment]
Mirad! encontre la solucion! aparece los achivos de los perfiles esta corruptos! :O 
Solo hay que borralo y ejecutar el launcher y te creo uno nuevo. 
;)

-VG

**Comment by HeberonYT** [comment]
@DANIELXDXD @VigilantesG 
Efectivamente, los perfiles no cargan cuando se corrompen, eso sucede solo a los usuarios No Premium y es causado por que el perfil es leído por diferentes lanzadores No Premium y eso hace que se corrompan.
La solución es ir a la ubicación de la instancia, abrir la carpeta .minecraft y borrar el archivo "launcher_profiles.json".
Después ejecutar el lanzador de su preferencia y crea un nuevo perfil para arrancar el juego.
