### ISSUE TITLE
Problema con Launcher Premiun v2.8.3

### ISSUE THREAD

**Issue by KebiDBZ** [HeberonYT/MultiMinecraft#70]
Cuando le doy a "play" me sale este error y no deja abrir el Launcher
![Error](https://user-images.githubusercontent.com/62112858/76546562-80e4a300-646a-11ea-8842-6dc420c5bfb4.png)

**Comment by SrManrique** [comment]
hola, yo tengo el mismo problema

**Comment by HeberonYT** [comment]
Debes descargar la ultima versión disponible desde el sitio oficial.

https://heberon.com/multiminecraft/download
