### ISSUE TITLE
Problema con Multiminecraft 2 Deluxe Edition v.2.8.3.0

### ISSUE THREAD

**Issue by Manu145324352** [HeberonYT/MultiMinecraft#71]
Al intentar ejecutar el launcher, me aparece este error y no me deja ejecutarlo.
He mirado y el java está instalado correctamente y es el adecuado.
Si alguien me puede ayudar, muchas gracias y un saludo.
![Captura de pantalla (2)](https://user-images.githubusercontent.com/62188863/76690381-b098d400-663f-11ea-9817-1e2ee3efaa8a.png)

**Comment by HeberonYT** [comment]
Prueba a descargar la ultima versión desde el sitio de MultiMine y en ventana Ajustes presiona actualizar todos los lanzadores.
