### ISSUE TITLE
Error code: 001

### ISSUE THREAD

**Issue by belce6** [HeberonYT/MultiMinecraft#72]
Al instalar el modpack Planeta Vegeta 7 me salta este error aunque tengo las ultimas actualizaciones
![1](https://user-images.githubusercontent.com/62276631/76825431-ba196c00-67f8-11ea-9268-49b84803b618.png)
![2](https://user-images.githubusercontent.com/62276631/76825433-bab20280-67f8-11ea-820a-a38f9a4223fc.png)

**Comment by HeberonYT** [comment]
@belce6 hay una versión mas reciente que la que usas, y en unas horas será liberada la versión 2.8.5 que corrige aun mas problemas.

**Comment by HeberonYT** [comment]
Si no te aparece el mensaje de la nueva versión, puedes descargarla he instalarla manualmente, para eso visita el sitio oficial de MultiMinecraft.
