### ISSUE TITLE
Problema con forge

### ISSUE THREAD

**Issue by Shelterlesst** [HeberonYT/MultiMinecraft#73]
Hola, tengo un problema con la instalación de minecraft forge a partir de la 1.13 en adelante
cuando me debería de aparecer la ventana de instalación automática no me aparece y se abre directamente el archivo .Rar
Ayuda

**Comment by crackgamer** [comment]
Hola tengo un problema abri el launcher entre a minecraft y me aparecio esto 
Se produjo un error durante la inicialización de VM
No se pudo reservar suficiente espacio para el montón de objetos 2097152KB
Advertencia de la máquina virtual del cliente Java HotSpot (TM): el uso de CMS incremental está en desuso y es probable que se elimine en una versión futura

**Comment by crackgamer** [comment]
ayudaaaaaaaaaaaaaaaaa

**Comment by AleChris20** [comment]
tengo un problema y es que la instalar crear una carpeta con Forge, no se crea la .minecraft y a la otra de instalar el forge, me dice que no hay carpeta .minecraft

**Comment by HeberonYT** [comment]
@Shelterlesst eso sucede porque los archivos .jar están vinculados a ejecutarse con winrar y no con java, para solucionarlo utiliza esta herramienta gratuita que solo debes ejecutarla.

https://johann.loefflmann.net/en/software/jarfix/index.html
