### ISSUE TITLE
Error con Java Script Machine Launcher

### ISSUE THREAD

**Issue by JoilerDGT** [HeberonYT/MultiMinecraft#74]
Al iniciar una instancia sale esto:
![r](https://user-images.githubusercontent.com/49568679/81461336-9cb9ac00-9170-11ea-9f04-1b567d5dbf0d.png)

**Comment by HeberonYT** [comment]
Supongo que ese lanzador seleccionado no está descargado del todo, puedes actualizar los lanzadores en la ventana "Ajustes" y selecciona la pestaña "Minecraft", allí presiona el botón "Actualizar lanzadores."
