### ISSUE TITLE
Cuando se instala, se borra 

### ISSUE THREAD

**Issue by Neidas0** [HeberonYT/MultiMinecraft#75]
Hola Heberon esto le pasa a un amigo, cuando el lo instala se abre despues de la instalacion, pero no hay rastro de multiminecraft ni en el escritorio ni en AppData, tambien cuando lo abre con la opcion del instalador, pone que no hay conexion a internet, esto pasa estando con cable o con Wi-Fi

**Comment by HeberonYT** [comment]
Este fallo no lo he visto, supongo que será algún problema del ordenador de tu amigo o su conexión.
Al instalar la aplicación debe crearse un acceso directo en el escritorio, si no se crea entonces puedes crearlo manualmente abriendo la carpeta donde se ha instalado MultiMine y creando un acceso directo al archivo MultiMinecraft Deluxe.exe

Si esto no soluciona el problema, graba un pequeño vídeo o cuelga imágenes que muestren el problema.
