### ISSUE TITLE
me da error en el programa

### ISSUE THREAD

**Issue by goku333Xx** [HeberonYT/MultiMinecraft#76]
lo que pasa es que pongo mods y la version para esos mods y al terminar y ejecutar dice error no se a encontrado el archivo json

**Comment by goku333Xx** [comment]
no se que hacer :V

**Comment by HeberonYT** [comment]
Esto supongo que te ocurre al instalar forge, no poner mods.
De ser así, será solucionado en la siguiente actualización de MultiMine.
