### ISSUE TITLE
Problema al Crear Instancia

### ISSUE THREAD

**Issue by KaitouRider** [HeberonYT/MultiMinecraft#77]
Buenas.
Tengo un problema al intentar crear una Instancia de la ver. 1.12.2 con Forge y es que, al crearla, me sale este mensaje "Ocurrió un problema al crear la instancia! No se ha podido encontrar el archivo JSON de la versión indicada: version.json"
La instancia se crea pero me abre la ultima versión de Minecraft.
Ademas probé a copiar la carpeta .minecraft de otra instancia antigua y conseguí que me abriera en la ver. 1.12.2 pero, al reiniciar el pc, la instancia desaparece sola.
Podrías echarle un ojo?
P.D. La version de Forge que le pongo es la 14.23.5.2854 y el OptiFine la 1.12.2 HD U F5

**Comment by Jorgegiral** [comment]
Me estaba ocurriendo el mismo problema, asi que baje la version del forge a la 14.23.5.2847 y ya me la dejo instalada

**Comment by Alborongo** [comment]
A mi me pasó igual...

**Comment by EsdrasMujica** [comment]
A mi también me pasa igual.

**Comment by HeberonYT** [comment]
Gracias por reportar, este problema se debe a que las ultimas 3 versiones de forge han cambiado la forma de instalarse, pero ya esta agregado el soporte en la aproxima versión de MultiMine (2.8.5), será liberada en breve.

**Comment by HeberonYT** [comment]
Solucionado en la ultima versión de MultiMine.
