### ISSUE TITLE
[ModManager] Background worker esta ocupado

### ISSUE THREAD

**Issue by RubenPX** [HeberonYT/MultiMinecraft#79]
![image](https://user-images.githubusercontent.com/23123160/95838012-917f3380-0d41-11eb-9f5c-65f4d9d88511.png)

he investigado el error un poco, y al parecer cuando se presenta una solicitud 404, el background worker se queda pillado y no muestra al usuario que no se ha podido cargar la pagina o reintentalo de nuevo

También tengo que decir que uso un proxy privado e igual puede darme algunas veces un 404 aleatoriamente

versión: 2.9.3.0

**Comment by HeberonYT** [comment]
Eso es muy extraño, porque antes de asignarle una tarea debe abortar la acción actual para después ejecutarlo con la nueva tarea, asi que literalmente no debería aparecer que está ocupado porque lo abortó antes. Voy a examinarlo más adelante, gracias por el reporte.
________________________________

**Comment by HeberonYT** [comment]
Hola de nuevo, hasta el momento no he logrado replicar este error. Si volviera a ocurrir, dímelo.
Gracias por el reporte.
