### ISSUE TITLE
Libreria de mods

### ISSUE THREAD

**Issue by Test83318** [HeberonYT/MultiMinecraft#8]
Yo tenía la issue #4  y buscando la opción de mover el registro de la carpeta .minecraft vi que estaba el archivo lista1 y ví que era la librería de mods.
Vi que era un archivo separado con * y pensé lo podría descomprimir(separar las columnas).
Pues pensé que hizá con algún sistema se pudiera añadir mods, por ejemplo un mod que haya hecho yo(que no es el caso).
P.D.Sé que puse la issue 5 , perdón por mencionar una que no era

**Comment by HeberonYT** [comment]
Hola!
Esa lista es de mods, pero no esta del todo actualizada, se jara en el futuro, y no es posible añadir mods por tu cuenta a la lista, ya que es descargada cada que se inicia la aplicación.

**Comment by Test83318** [comment]
Quería decir alguna cosa como un bot de discord, o un form para actualizar el archivo que se descarga
