### ISSUE TITLE
No se abre ningún launcher aparte del premium version antigua

### ISSUE THREAD

**Issue by MattzDrake** [HeberonYT/MultiMinecraft#81]
No se que pasa pero cuando creo una instancia ya sea vanilla o sea una version con forge ningun launcher se ejecuta, quiero ejecutar con el launcher YoFenix pero nada, ya probe con todos pero nada, solo la version premium antigua pero no cuento con ninguna cuenta premium

**Comment by HeberonYT** [comment]
Hola, actualiza los lanzadores desde loas ajustes de MultiMinecraft, eso forzará la descarga  de todos los archivos.
