### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by cbarroso97** [HeberonYT/MultiMinecraft#82]
Hola intento instalar cualquier cosa y no me deja siempre me sale esto............
![image](https://user-images.githubusercontent.com/75247570/100593177-60aa8c00-32f8-11eb-9536-46e9f52c900e.png)

**Comment by HeberonYT** [comment]
Cambia de lanzador, los perfiles no se muestran porque fueron creados con un lanzador superior.
Otra opción es borrar el archivo "launcher_profiles.json" que está dentro de la carpeta .minecraft, eso significa que deberás crear un perfil nuevo.
