### ISSUE TITLE
herebon, un mensaje

### ISSUE THREAD

**Issue by borjita2019** [HeberonYT/MultiMinecraft#84]
lo que digo es esto: poner un launcher en la instancia "1" tiene launcher fenix como predeterminado, pero el "2" tiene titan launcher (por ejemplo) y que puedas poner diferentes launchers de predeterminado en diferentes instancias

**Comment by HeberonYT** [comment]
por favor, responde en el mismo mensaje, no debes crear un ticket para preguntar.
Sobre tu pregunta, no se puede establecer un launcher por default a cada instancia, el launcher por default solo se puede establecer 1 en los ajustes de MultiMinecraft.

**Comment by borjita2019** [comment]
f
