### ISSUE TITLE
[MODMANAGER]

### ISSUE THREAD

**Issue by MONSTER0AWP** [HeberonYT/MultiMinecraft#86]
HAY UN PROBLEMA CON LA VERIFICACIÓN DE HUMANO NO PROCESA BIEN LAS RESPUESTAS

**Comment by HeberonYT** [comment]
Hola, podrías mencionar más detalles del problema?
Que pasos realizas, que venta se muestra, que dice el mensaje de error, o que se ve en pantalla?
Si fuera posible agregar una foto o captura también ayudará.
________________________________

**Comment by HeberonYT** [comment]
Hola de nuevo, lo he revisado en diferentes ordenadores y no encuentro ningún problema con el captcha, cuando lo resuelvas correctamente no volverá a solicitarlo.
Aquí una captura de la prueba que hice. 
![Screenshot_1](https://user-images.githubusercontent.com/13698597/109101149-cc2faa00-76eb-11eb-80a5-62d5be898e9a.png)
