### ISSUE TITLE
error en servidor remoto

### ISSUE THREAD

**Issue by laicanoni** [HeberonYT/MultiMinecraft#87]
disculpe la molestia, desde hace mas de  una semana tengo un problema.
las instancias de Project ozone 2,  #save the ages y sky factory 4 no cargan devido al error 001, error en servidor remoto.
Me ayudaria mucho si me lograran dar alguna solucion

@HeberonYT #
![eroror ](https://user-images.githubusercontent.com/79945737/109727332-c289c480-7b79-11eb-8b83-88bb3c067636.png)

![eroror 2](https://user-images.githubusercontent.com/79945737/109727347-cae1ff80-7b79-11eb-85c2-ab1791c225ba.png)

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte, esto es causado por un cambio en los archivos del host remoto, pero ya esta resuelto.
