### ISSUE TITLE
Launcher no se ejecuta y abre una ventana de Winrar

### ISSUE THREAD

**Issue by MauRyTo** [HeberonYT/MultiMinecraft#88]
Hola quisiera saber como solucionar este problema, y es que cuando ejecuto una instancia abre una ventana con archivos como se puede ver en la imagen pero ya he extraído esos archivos en la carpeta correspondiente al Lanzador (Launcher fenix) y sigue apareciendo esa ventana ¿Qué puedo hacer para solucionarlo?, cabe aclarar que la aplicación la acabo de actualizar.

![image](https://user-images.githubusercontent.com/81054837/111888683-61992380-89a4-11eb-93d0-48ebc2e87413.png)

**Comment by HeberonYT** [comment]
Hola, en unos minutos que esté en mi PC te respondo, porque ya se a que se debe y tienes que hacer unos pasos para solucionarlo, dame 5 minutos.

**Comment by MauRyTo** [comment]
emm si no hay problema soy paciente, perdón por la tardanza.

**Comment by HeberonYT** [comment]
El problema ocurre porque en tu ordenador tienes establecido que los archivos .jar se abran con WinRAR y debería ser con Java.
Utiliza este programa para resolver el problema, la pagina te dice las instrucciones, solo es ejecutarlo y listo.

https://johann.loefflmann.net/en/software/jarfix/index.html
