### ISSUE TITLE
al abrir tras la nueva actualizacion

### ISSUE THREAD

**Issue by JUANP059** [HeberonYT/MultiMinecraft#90]
descargue la nueva actualizacion ya de la forma automatica y manual pero me sigue pidiendo actualizar y al terminar sale este error
![image](https://user-images.githubusercontent.com/81502494/112743167-9be16280-8f5a-11eb-8b26-68e6c05d0349.png)

**Comment by HeberonYT** [comment]
Hola, ejecuta la aplicación como administrador, eso debería permitir que se instale la nueva versión.

**Comment by JUANP059** [comment]
ya lo ejecute como administrador y sigue presentando el mismo iconveniente

**Comment by JUANP059** [comment]
espera he solucionado el problema abriendo la carpeta updater y ejecutando el updater solo como administrador.

**Comment by HeberonYT** [comment]
muy bien, gracias por la info, haré cambios para resolverlo en la siguiente actualización.
