### ISSUE TITLE
Error al Actualizar

### ISSUE THREAD

**Issue by MasckedRider** [HeberonYT/MultiMinecraft#91]
Buenas. He abierto el MultiMinecraft y se ha puesto a actulizar. Ha ido todo normal hasta que la barra de descarga ha terminado y se ha cerrado, entonces me ha salido un mensaje de error de que no tiene acceso a la ruta de un archivo.
He probado a ejecutarlo como administrador pero sigue igual.
Como puedo solucionarlo?
Adjunto imagen del mensaje.
![Sin título](https://user-images.githubusercontent.com/81813306/113416867-7ae99900-93c2-11eb-9d7b-07d4a113fb04.png)
Gracias.

**Comment by HeberonYT** [comment]
Hola, este problema me lo han reportado mucho últimamente, ya tengo una solución para ello, en 30 minutos haré un cambio de archivos y necesito que pruebes a actualizar de nuevo para verificar que se ha solucionado.

Recuerda, en 30 minutos a partir de ahora, si es posible te pido vuelvas a comentar el resultado.

**Comment by MasckedRider** [comment]
Perdon. Aprobeche para hacer otras cosas y no fue hasta mas tarde que lo lei -.-U
Muchas gracias por la rapidez y tu trabajo. Ya se ha actualizado correctamente ^^

**Comment by HeberonYT** [comment]
Genial.
