### ISSUE TITLE
Crear instancia - Forge (Error)

### ISSUE THREAD

**Issue by PokeMy14** [HeberonYT/MultiMinecraft#92]
Buenas, aqui le traigo un muy posible error. Es mi primera instalación del programa y por lo tanto supongo tener la version mas reciente del mismo.

Al crear una estancia en Forge, a los pocos segundos de entrar en la ventana de creación de la estancia me sale un mensaje que dice lo siguiente;

La longitud no puede ser inferior a cero.
Nombre del parametro: length

Generalmente no te da tiempo a editar nada antes de que este mensaje aparezca en tu pantalla. Luego de esto vuelves a la pantalla principal del programa.

Espero haber sido detallado y que sirva de ayuda, un placer Heberon.

**Comment by PokeMy14** [comment]
Bien, probando un poco mas el programa llegué a la conclusión de que en la instalación o en el propio programa no reconoce las versiones de Forge, asi que java obtiene un valor nulo y salta el mensaje de error. En otras palabras, la opcion Forge esta vacia en todos los accesos a el. Necesita una instalación manual.

**Comment by HeberonYT** [comment]
Hola, gracias por tu reporte y la información detallada.
Justo ahora he lanzado una nueva actualización de MultiMinecraft, porque hoy Forge modificó el sistema de consulta de versiones, rompiendo la aplicación, pero ya está solucionado.

Hazme saber si la nueva versión corrige el problema.

**Comment by PokeMy14** [comment]
Por el momento ese error en concreto
