### ISSUE TITLE
error de lanzador 

### ISSUE THREAD

**Issue by MONSTER0AWP** [HeberonYT/MultiMinecraft#93]
al prender mi computadora me di cuenta que no se encontraba el acceso directo de la app pero ya no puedo jugar nose que hacer ya me metí en la raiz de la app y no encuentro el ejecutable

**Comment by HeberonYT** [comment]
Hola, recientemente se reportó que una actualización de Windows 10 eliminó la aplicación porque detecta un virus, claro que no hay ningún virus, pero la actualización de Windows bloqueo varias aplicaciones.
Te recomiendo agregar a las exclusiones la aplicacion de MultiMinecraft, eso lo haces desde el panel de Windows Defender, busca en la notificaciones o eventos recientes el aviso de que eliminó MultiMinecraft, y una de las opciones es agregar a las exclusiones.

Después de eso puedes reinstalar multiminecraft en la misma ubicación donde estaba antes, para que sigas utilizando tus instancias almacenadas.
